wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1675967526.638728
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 19
      - 23
      - 37
      4: 3.7.10
      5: 0.13.1
      8:
      - 5
epsilon:
  desc: null
  value: 1.0e-08
gcs_path:
  desc: null
  value: gs://genformer_data/expanded_originals/196k
gcs_path_TSS:
  desc: null
  value: gs://genformer_data/expanded_originals/196k/human/tfrecords_tss
gradient_clip:
  desc: null
  value: 0.2
heads_channels:
  desc: null
  value:
    human: 5313
    mouse: 1643
lr_base:
  desc: null
  value: 0.0005
min_delta:
  desc: null
  value: 1.0e-05
model_save_basename:
  desc: null
  value: enformer_performer_230209
model_save_dir:
  desc: null
  value: gs://picard-testing-176520/enformer_full/models
num_epochs:
  desc: null
  value: 100
patience:
  desc: null
  value: 50
subsets:
  desc: null
  value: exclude_chip
total_steps:
  desc: null
  value: 566
tpu:
  desc: null
  value: node-5
use_enformer_weights:
  desc: null
  value: false
val_examples_TSS:
  desc: null
  value: 100
val_steps_TSS:
  desc: null
  value: 12
warmup_frac:
  desc: null
  value: 0.146
