wandb_version: 1

epsilon:
  value: 1.0e-08
gradient_clip:
  value: 0.2
heads_channels:
  value:
    human: 5313
    mouse: 1643
lr_base:
  value: 0.0005
subsets:
  value: exclude_chip
use_enformer_weights:
  value: false
